Задача 2. Построение детерминированного конечного автомата по регулярному выражению и недетерминированного конечного автомата по графу
RozhkovAleksandr/formal-lang-course pull request #2
Opened 2024-09-16 17:10 UTC by RozhkovAleksandr

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
  - Требуемая функция:
  ```python
  def regex_to_dfa(regex: str) -> DeterministicFiniteAutomaton:
      pass
  ```
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](#задача-1-инициализация-рабочего-окружения) (загруженный из набора данных по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
  - Требуемая функция:
  ```python
  def graph_to_nfa(
    graph: MultiDiGraph, start_states: Set[int], final_states: Set[int]
  ) -> NondeterministicFiniteAutomaton:
      pass
  ```
- [x] Добавить собственные тесты при необходимости.

2024-09-20 21:13 UTC, bachish commented
Вы не назначили ревью на меня ;((

2024-09-20 21:49 UTC, bachish requested changes

2024-09-20 21:49 UTC, bachish commented on project/task2.py
> +print(nfa._states)
Кажется, это лишнее

2024-09-20 21:49 UTC, bachish commented on tests/test_task2.py
> +    assert dfa.accepts("")
А здесь, наоборот, маловато.

2024-09-28 22:01 UTC, bachish commented
Запрос вижу. Исправьте замечания выше -- зачту без штрафа.

2024-09-30 15:55 UTC, RozhkovAleksandr commented
Здравствуйте, спасибо за правки! 

Тот лишний код я убрал. По поводу тестов во втором задании было сказано следующее: "Добавить собственные тесты при необходимости".

2024-10-05 14:23 UTC, bachish approved these changes

2024-10-05 14:39 UTC, bachish commented
> Потому я подумал, что можно много их не писать)

Действительно, много тестов не нужно. Но приветствуется, если вы покроете основную функциональность или интересные краевые случаи.

2024-10-06 15:45 UTC, merged